name: Lint and Test Website   # Name des Workflows, erscheint in GitHub Actions

on:                           # Wann der Workflow ausgeführt wird
  push:                       # Bei jedem Push
    branches:                 # aber nur auf bestimmten Branches
      - development           # dein Entwicklungszweig
      - main                  # optional: auch auf main
  pull_request:               # bei jedem PR
    branches:
      - main                  # PRs gegen main sollen Tests auslösen

jobs:                         # Sammlung von Jobs
  lint:                       # Job-Name
    runs-on: ubuntu-latest    # GitHub Actions Runner (Linux VM)

    steps:                    # Schritte im Job
      - name: Checkout code
        uses: actions/checkout@v4   # Holt dein Repo in den Runner

      - name: Build Docker image
        run: docker build -t mysite:ci -f Webseite/Dockerfile .   # Baut Container aus Webseite/

      - name: Install Node and linters
        # Installiert Node.js und die benötigten Linter (inklusive Stylelint, HTMLHint & Stylelint-Konfiguration)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y nodejs npm
          sudo npm install -g htmlhint stylelint
          sudo npm install -g stylelint-config-standard


      - name: Run htmlhint
        run: htmlhint ./Webseite                    # Prüft HTML-Dateien auf Syntaxfehler, fehlede oder unsaubere Strukturen, etc.

      - name: Run stylelint
        run: stylelint "./Webseite/**/*.css"        # Prüft CSS-Dateien auf Fehler, Stilverletzungen, etc.

      - name: Show Docker image size
        run: docker images mysite:ci --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"  # Zeigt die Größe des erstellten Docker-Images an